export type AiToneId =
    | 'friendly'
    | 'professional'
    | 'informative'
    | 'humorous'
    | 'inspirational'
    | 'empathetic'
    | 'authoritative'
    | 'playful'
    | 'educational'
    | 'urgent'
