FROM node:20-alpine AS base

RUN apk add --no-cache libc6-compat
WORKDIR /app

FROM base AS deps

COPY package.json package-lock.json ./
RUN npm ci


FROM base AS build

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_FACEBOOK_CLIENT_ID
ARG NEXT_PUBLIC_FACEBOOK_REDIRECT_URL
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID
ARG NEXT_PUBLIC_INSTAGRAM_APP_ID
ARG NEXT_PUBLIC_INSTAGRAM_REDIRECT_URI
ARG NEXT_PUBLIC_LINKEDIN_APP_ID
ARG NEXT_PUBLIC_LINKEDIN_REDIRECT_URL
ARG NEXT_PUBLIC_PINTEREST_ID
ARG NEXT_PUBLIC_PINTEREST_REDIRECT_URL
ARG NEXT_PUBLIC_STRIPE_PRO_PLAN_MONTHLY_URL
ARG NEXT_PUBLIC_STRIPE_PRO_PLAN_MONTHLY_URL_DEV
ARG NEXT_PUBLIC_STRIPE_PRO_PLAN_YEARLY_URL
ARG NEXT_PUBLIC_STRIPE_PRO_PLAN_YEARLY_URL_DEV
ARG NEXT_PUBLIC_STRIPE_STARTER_PLAN_MONTHLY_URL
ARG NEXT_PUBLIC_STRIPE_STARTER_PLAN_MONTHLY_URL_DEV
ARG NEXT_PUBLIC_STRIPE_STARTER_PLAN_YEARLY_URL
ARG NEXT_PUBLIC_STRIPE_STARTER_PLAN_YEARLY_URL_DEV
ARG NEXT_PUBLIC_THREADS_CLIENT_ID
ARG NEXT_PUBLIC_THREADS_REDIRECT_URL
ARG NEXT_PUBLIC_TIKTOK_ID
ARG NEXT_PUBLIC_TIKTOK_REDIRECT_URL
ARG NEXT_PUBLIC_X_ID
ARG NEXT_PUBLIC_X_REDIRECT_URL
ARG NEXT_PUBLIC_YOUTUBE_REDIRECT_URL
ARG NEXT_PUBLIC_ENVIRONMENT

ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_FACEBOOK_CLIENT_ID=$NEXT_PUBLIC_FACEBOOK_CLIENT_ID
ENV NEXT_PUBLIC_FACEBOOK_REDIRECT_URL=$NEXT_PUBLIC_FACEBOOK_REDIRECT_URL
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID
ENV NEXT_PUBLIC_INSTAGRAM_APP_ID=$NEXT_PUBLIC_INSTAGRAM_APP_ID
ENV NEXT_PUBLIC_INSTAGRAM_REDIRECT_URI=$NEXT_PUBLIC_INSTAGRAM_REDIRECT_URI
ENV NEXT_PUBLIC_LINKEDIN_APP_ID=$NEXT_PUBLIC_LINKEDIN_APP_ID
ENV NEXT_PUBLIC_LINKEDIN_REDIRECT_URL=$NEXT_PUBLIC_LINKEDIN_REDIRECT_URL
ENV NEXT_PUBLIC_PINTEREST_ID=$NEXT_PUBLIC_PINTEREST_ID
ENV NEXT_PUBLIC_PINTEREST_REDIRECT_URL=$NEXT_PUBLIC_PINTEREST_REDIRECT_URL
ENV NEXT_PUBLIC_STRIPE_PRO_PLAN_MONTHLY_URL=$NEXT_PUBLIC_STRIPE_PRO_PLAN_MONTHLY_URL
ENV NEXT_PUBLIC_STRIPE_PRO_PLAN_MONTHLY_URL_DEV=$NEXT_PUBLIC_STRIPE_PRO_PLAN_MONTHLY_URL_DEV
ENV NEXT_PUBLIC_STRIPE_PRO_PLAN_YEARLY_URL=$NEXT_PUBLIC_STRIPE_PRO_PLAN_YEARLY_URL
ENV NEXT_PUBLIC_STRIPE_PRO_PLAN_YEARLY_URL_DEV=$NEXT_PUBLIC_STRIPE_PRO_PLAN_YEARLY_URL_DEV
ENV NEXT_PUBLIC_STRIPE_STARTER_PLAN_MONTHLY_URL=$NEXT_PUBLIC_STRIPE_STARTER_PLAN_MONTHLY_URL
ENV NEXT_PUBLIC_STRIPE_STARTER_PLAN_MONTHLY_URL_DEV=$NEXT_PUBLIC_STRIPE_STARTER_PLAN_MONTHLY_URL_DEV
ENV NEXT_PUBLIC_STRIPE_STARTER_PLAN_YEARLY_URL=$NEXT_PUBLIC_STRIPE_STARTER_PLAN_YEARLY_URL
ENV NEXT_PUBLIC_STRIPE_STARTER_PLAN_YEARLY_URL_DEV=$NEXT_PUBLIC_STRIPE_STARTER_PLAN_YEARLY_URL_DEV
ENV NEXT_PUBLIC_THREADS_CLIENT_ID=$NEXT_PUBLIC_THREADS_CLIENT_ID
ENV NEXT_PUBLIC_THREADS_REDIRECT_URL=$NEXT_PUBLIC_THREADS_REDIRECT_URL
ENV NEXT_PUBLIC_TIKTOK_ID=$NEXT_PUBLIC_TIKTOK_ID
ENV NEXT_PUBLIC_TIKTOK_REDIRECT_URL=$NEXT_PUBLIC_TIKTOK_REDIRECT_URL
ENV NEXT_PUBLIC_X_ID=$NEXT_PUBLIC_X_ID
ENV NEXT_PUBLIC_X_REDIRECT_URL=$NEXT_PUBLIC_X_REDIRECT_URL
ENV NEXT_PUBLIC_YOUTUBE_REDIRECT_URL=$NEXT_PUBLIC_YOUTUBE_REDIRECT_URL
ENV NEXT_PUBLIC_ENVIRONMENT=$NEXT_PUBLIC_ENVIRONMENT

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm run build


FROM base AS prod-deps

COPY package.json package-lock.json ./
RUN npm ci --omit=dev


FROM node:20-alpine AS runner

RUN apk add --no-cache libc6-compat \
    && addgroup -S nodejs \
    && adduser -S nextjs -G nodejs

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

COPY --from=prod-deps /app/node_modules ./node_modules
COPY package.json package-lock.json ./
COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public
COPY --from=build /app/content ./content
COPY --from=build /app/next.config.* ./
COPY --from=build /app/content-collections.ts ./

RUN chown -R nextjs:nodejs /app
USER nextjs

EXPOSE 3000

CMD ["npm", "run", "start"]
