export const FALLBACK_TIMEZONES = [
    // UTC−11 to UTC−03
    'Pacific/Midway',
    'Pacific/Honolulu',
    'America/Anchorage',
    'America/Los_Angeles',
    'America/Denver',
    'America/Chicago',
    'America/Mexico_City',
    'America/Bogota',
    'America/Lima',
    'America/New_York',
    'America/Toronto',
    'America/Caracas',
    'America/Santiago',
    'America/Sao_Paulo',
    'America/Buenos_Aires',
    // UTC−02 to UTC+02
    'Atlantic/Azores',
    'UTC',
    'Europe/London',
    'Europe/Dublin',
    'Europe/Lisbon',
    'Africa/Casablanca',
    'Africa/Lagos',
    'Europe/Paris',
    'Europe/Amsterdam',
    'Europe/Berlin',
    'Europe/Rome',
    'Europe/Warsaw',
    'Europe/Athens',
    'Europe/Istanbul',
    'Africa/Cairo',
    'Asia/Jerusalem',
    'Africa/Johannesburg',
    'Europe/Moscow',
    // UTC+03 to UTC+06:30
    'Asia/Dubai',
    'Asia/Karachi',
    'Asia/Kolkata',
    'Asia/Kathmandu',
    'Asia/Dhaka',
    'Asia/Yangon',
    'Asia/Bangkok',
    'Asia/Jakarta',
    // UTC+07 to UTC+09:30
    'Asia/Singapore',
    'Asia/Shanghai',
    'Asia/Hong_Kong',
    'Asia/Taipei',
    'Asia/Kuala_Lumpur',
    'Asia/Manila',
    'Australia/Perth',
    'Asia/Seoul',
    'Asia/Tokyo',
    'Australia/Darwin',
    // UTC+10 to UTC+14
    'Australia/Adelaide',
    'Australia/Sydney',
    'Pacific/Guam',
    'Pacific/Noumea',
    'Pacific/Fiji',
    'Pacific/Auckland',
    'Pacific/Chatham',
    'Pacific/Tongatapu',
    'Pacific/Kiritimati',
] as const

export type FallbackTimezone = (typeof FALLBACK_TIMEZONES)[number]
