export enum ErrorCode {
    // General
    UNKNOWN_ERROR = 'UNKNOWN_ERROR', // 500
    BAD_REQUEST = 'BAD_REQUEST', // 400
    UNAUTHORIZED = 'UNAUTHORIZED', // 401
    FORBIDDEN = 'FORBIDDEN', // 403
    NOT_FOUND = 'NOT_FOUND', // 404
    CONFLICT = 'CONFLICT', // 409

    // Auth
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS', // 401
    TOKEN_EXPIRED = 'TOKEN_EXPIRED', // 401
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS', // 409

    // Content / Scheduling
    SCHEDULE_CONFLICT = 'SCHEDULE_CONFLICT', // 409 - same time/post
    CONTENT_VALIDATION_FAILED = 'CONTENT_VALIDATION_FAILED', // 400
    PLATFORM_UNAUTHORIZED = 'PLATFORM_UNAUTHORIZED', // 403 - e.g., not linked IG/Twitter

    // Files / Media
    FILE_TOO_LARGE = 'FILE_TOO_LARGE', // 413
    UNSUPPORTED_FILE_TYPE = 'UNSUPPORTED_FILE_TYPE', // 415
    FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED', // 500

    // Rate limiting / Quotas
    RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED', // 429
    PLAN_LIMIT_REACHED = 'PLAN_LIMIT_REACHED', // 403 - e.g., max posts/month
    DUPLICATES = 'DUPLICATES',

    // Platform Daily Limits
    TIKTOK_DAILY_LIMIT = 'TIKTOK_DAILY_LIMIT', // 429
    YOUTUBE_DAILY_LIMIT = 'YOUTUBE_DAILY_LIMIT', // 429
    PINTEREST_DAILY_LIMIT = 'PINTEREST_DAILY_LIMIT', // 429
    INSTAGRAM_DAILY_LIMIT = 'INSTAGRAM_DAILY_LIMIT', // 429
    THREADS_DAILY_LIMIT = 'THREADS_DAILY_LIMIT', // 429
    FACEBOOK_DAILY_LIMIT = 'FACEBOOK_DAILY_LIMIT', // 429
    BLUESKY_DAILY_LIMIT = 'BLUESKY_DAILY_LIMIT', // 429
    LINKEDIN_DAILY_LIMIT = 'LINKEDIN_DAILY_LIMIT', // 429
    GOOGLE_DAILY_LIMIT = 'GOOGLE_DAILY_LIMIT', // 429
    X_DAILY_LIMIT = 'X_DAILY_LIMIT', // 429
}
